modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/FarmingForBlockheads/issues"

[[mods]]
modId="farmingforblockheads"
version="${file.jarVersion}"
displayName="Farming for Blockheads"
displayURL="https://blay09.net/mods/farmingforblockheads"
logoFile="farmingforblockheads-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Adds a seed market with a search bar and a scrolling grid and more farming utilities.
'''

[[dependencies.farmingforblockheads]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.farmingforblockheads]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.farmingforblockheads]]
    modId="balm"
    mandatory=true
    versionRange="[6.0.0,)"
    ordering="NONE"
    side="BOTH"
