modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/blay09/FarmingForBlockheads/issues"
displayURL="https://minecraft.curseforge.com/projects/farming-for-blockheads"
authors="BlayTheNinth"

[[mods]]
modId="farmingforblockheads"
version="${file.jarVersion}"
displayName="Farming for Blockheads"
description='''
Adds a seed market with a search bar and a scrolling grid and more farming utilities.
'''
